# Generated by Django 3.0.2 on 2020-01-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogging_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogging',
            name='patient_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
