# Generated by Django 3.0.2 on 2020-01-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogging',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
